name: ffd
description: flutter fast devlopment packages
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #toast https://pub.flutter-io.cn/packages/oktoast
  oktoast: 3.1.3+1
  #退到后台 https://pub.flutter-io.cn/packages/move_to_background
  move_to_background: 1.0.2
  #网络请求 https://pub.flutter-io.cn/packages/dio
  dio: 4.0.0
  #状态管理 https://pub.flutter-io.cn/packages/provider
  provider: 6.0.1
  #加密算法 https://pub.flutter-io.cn/packages/crypto
  crypto: 3.0.1
  #路径获取 https://pub.flutter-io.cn/packages/path_provider
  path_provider: 2.0.5
  #encoders and decoders  https://pub.flutter-io.cn/packages/convert
  convert: 3.0.1
  #下拉刷新 https://pub.flutter-io.cn/packages/pull_to_refresh
  pull_to_refresh: 2.0.0
  #工具 https://pub.flutter-io.cn/packages/flustars
  flustars: 2.0.1
  #动画库 https://pub.flutter-io.cn/packages/flutter_spinkit
  flutter_spinkit: 5.1.0

  #ffloat: 1.0.1
  #mk_drop_down_menu: 1.1.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
  plugin:
    androidPackage: com.sh.ffd
    pluginClass: FFDPlugin
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages

